wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    framework: huggingface
    huggingface_version: 4.5.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      4: 3.7.10
      5: 0.10.25
      6: 4.5.0
      8:
      - 1
      - 5
adafactor_beta1:
  desc: null
  value: null
adafactor_clip_threshold:
  desc: null
  value: 1.0
adafactor_decay_rate:
  desc: null
  value: -0.8
adafactor_eps:
  desc: null
  value:
  - 1.0e-30
  - 0.001
adafactor_relative_step:
  desc: null
  value: false
adafactor_scale_parameter:
  desc: null
  value: false
adafactor_warmup_init:
  desc: null
  value: false
adam_epsilon:
  desc: null
  value: 1.0e-08
best_model_dir:
  desc: null
  value: outputs/best_model
cache_dir:
  desc: null
  value: cache_dir/
config:
  desc: null
  value: {}
cosine_schedule_num_cycles:
  desc: null
  value: 0.5
custom_layer_parameters:
  desc: null
  value: []
custom_parameter_groups:
  desc: null
  value: []
dataloader_num_workers:
  desc: null
  value: 0
dataset_class:
  desc: null
  value: null
do_lower_case:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
dynamic_quantize:
  desc: null
  value: false
early_stopping:
  desc: null
  value: true
early_stopping_consider_epochs:
  desc: null
  value: false
early_stopping_delta:
  desc: null
  value: 0
early_stopping_metric:
  desc: null
  value: eval_loss
early_stopping_metric_minimize:
  desc: null
  value: true
early_stopping_patience:
  desc: null
  value: 3
encoding:
  desc: null
  value: null
eval_batch_size:
  desc: null
  value: 64
evaluate_during_training:
  desc: null
  value: true
evaluate_during_training_silent:
  desc: null
  value: true
evaluate_during_training_steps:
  desc: null
  value: 15000
evaluate_during_training_verbose:
  desc: null
  value: true
evaluate_each_epoch:
  desc: null
  value: true
evaluate_generated_text:
  desc: null
  value: false
fp16:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.001
length_penalty:
  desc: null
  value: 2.0
local_rank:
  desc: null
  value: -1
logging_steps:
  desc: null
  value: 50
manual_seed:
  desc: null
  value: null
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_seq_length:
  desc: null
  value: 196
max_steps:
  desc: null
  value: -1
model_class:
  desc: null
  value: T5Model
model_name:
  desc: null
  value: t5-small
model_type:
  desc: null
  value: t5
multiprocessing_chunksize:
  desc: null
  value: -1
n_gpu:
  desc: null
  value: 1
no_cache:
  desc: null
  value: false
no_save:
  desc: null
  value: false
not_saved_args:
  desc: null
  value: []
num_beams:
  desc: null
  value: 1
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 1
optimizer:
  desc: null
  value: Adafactor
output_dir:
  desc: null
  value: outputs/
overwrite_output_dir:
  desc: null
  value: true
polynomial_decay_schedule_lr_end:
  desc: null
  value: 1.0e-07
polynomial_decay_schedule_power:
  desc: null
  value: 1.0
preprocess_inputs:
  desc: null
  value: true
process_count:
  desc: null
  value: 1
quantized_model:
  desc: null
  value: false
repetition_penalty:
  desc: null
  value: 1.0
reprocess_input_data:
  desc: null
  value: true
save_best_model:
  desc: null
  value: true
save_eval_checkpoints:
  desc: null
  value: false
save_model_every_epoch:
  desc: null
  value: true
save_optimizer_and_scheduler:
  desc: null
  value: true
save_steps:
  desc: null
  value: -1
scheduler:
  desc: null
  value: constant_schedule_with_warmup
silent:
  desc: null
  value: false
skip_special_tokens:
  desc: null
  value: true
special_tokens_list:
  desc: null
  value: []
tensorboard_dir:
  desc: null
  value: null
thread_count:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
tokenizer_type:
  desc: null
  value: null
top_k:
  desc: null
  value: null
top_p:
  desc: null
  value: null
train_batch_size:
  desc: null
  value: 16
train_custom_parameters_only:
  desc: null
  value: false
use_cached_eval_features:
  desc: null
  value: false
use_early_stopping:
  desc: null
  value: false
use_hf_datasets:
  desc: null
  value: false
use_multiprocessed_decoding:
  desc: null
  value: true
use_multiprocessing:
  desc: null
  value: false
use_multiprocessing_for_evaluation:
  desc: null
  value: true
wandb_kwargs:
  desc: null
  value: {}
wandb_project:
  desc: null
  value: T5 mixed tasks - Binary, Multi-Label
warmup_ratio:
  desc: null
  value: 0.06
warmup_steps:
  desc: null
  value: 560
weight_decay:
  desc: null
  value: 0.0
